entity: product_stock
schema: products
description: Materialized view / table for quick stock info (or canonical inventory pointer)
attributes:
  product_id:
    type: uuid
    primary_key: true
    foreign_key:
      target: products.products.id
  available:
    type: integer
    nullable: false
    default: 0
  reserved:
    type: integer
    nullable: false
    default: 0
  updated_at:
    type: timestamp
    default: now()
