entity: product_variants
schema: products
description: Variants of a product (size, flavor)
attributes:
  id:
    type: uuid
    primary_key: true
    default: uuid_generate_v4()
  product_id:
    type: uuid
    nullable: false
    foreign_key:
      target: products.products.id
  name:
    type: string
    max_length: 120
    nullable: false
  extra_price:
    type: decimal
    precision: 10
    scale: 2
    default: 0.00
  sku:
    type: string
    max_length: 80
    nullable: true
  is_active:
    type: boolean
    default: true
  created_at:
    type: timestamp
    default: now()
