entity: products
schema: products
description: Products sold by businesses
attributes:
  id:
    type: uuid
    primary_key: true
    default: uuid_generate_v4()
  business_id:
    type: uuid
    nullable: false
    foreign_key:
      target: business.businesses.id
  sku:
    type: string
    max_length: 80
    nullable: true
    unique: true
  name:
    type: string
    max_length: 160
    nullable: false
  description:
    type: text
    nullable: true
  category_id:
    type: uuid
    foreign_key:
      target: products.categories.id
    nullable: true
  base_price:
    type: decimal
    precision: 10
    scale: 2
    nullable: false
    default: 0.00
  is_active:
    type: boolean
    default: true
  created_at:
    type: timestamp
    default: now()
