entity: categories
schema: products
description: Product categories
attributes:
  id:
    type: uuid
    primary_key: true
    default: uuid_generate_v4()
  business_id:
    type: uuid
    nullable: false
    foreign_key:
      target: business.businesses.id
  name:
    type: string
    max_length: 120
    nullable: false
  slug:
    type: string
    max_length: 120
    nullable: false
  created_at:
    type: timestamp
    default: now()
indexes:
  - columns: [business_id, slug]
    unique: true
